//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenlyPizzeriaWebUI.QueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/Contract.DTOs", ConfigurationName="QueryService.QueryService")]
    public interface QueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.datacontract.org/2004/07/Contract.DTOs/QueryService/ExecuteQuery", ReplyAction="http://schemas.datacontract.org/2004/07/Contract.DTOs/QueryService/ExecuteQueryRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.PageInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Paged<Contract.DTOs.OrderInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Pizza.GetAllPizzasQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Pizza.GetPizzaByIdQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Orders.GetOrderByIdQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Queries.Orders.GetUnshippedOrdersForCurrentCustomerQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.Pizza[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.Pizza))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.OrderInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.OrderInfo[]))]
        object ExecuteQuery(object query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.datacontract.org/2004/07/Contract.DTOs/QueryService/ExecuteQuery", ReplyAction="http://schemas.datacontract.org/2004/07/Contract.DTOs/QueryService/ExecuteQueryRe" +
            "sponse")]
        System.Threading.Tasks.Task<object> ExecuteQueryAsync(object query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceChannel : HeavenlyPizzeriaWebUI.QueryService.QueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceClient : System.ServiceModel.ClientBase<HeavenlyPizzeriaWebUI.QueryService.QueryService>, HeavenlyPizzeriaWebUI.QueryService.QueryService {
        
        public QueryServiceClient() {
        }
        
        public QueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object ExecuteQuery(object query) {
            return base.Channel.ExecuteQuery(query);
        }
        
        public System.Threading.Tasks.Task<object> ExecuteQueryAsync(object query) {
            return base.Channel.ExecuteQueryAsync(query);
        }
    }
}
