//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavenlyPizzeriaWebUI.CommandService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationError", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ValidationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/Contract.DTOs", ConfigurationName="CommandService.CommandService")]
    public interface CommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.datacontract.org/2004/07/Contract.DTOs/CommandService/Execute", ReplyAction="http://schemas.datacontract.org/2004/07/Contract.DTOs/CommandService/ExecuteRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HeavenlyPizzeriaWebUI.CommandService.ValidationError), Action="http://schemas.datacontract.org/2004/07/Contract.DTOs/CommandService/ExecuteValid" +
            "ationErrorFault", Name="ValidationError", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Commands.Orders.CreateOrderCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.Commands.Orders.ShipOrderCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeavenlyPizzeriaWebUI.CommandService.ValidationError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Contract.DTOs.Address))]
        void Execute(object command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.datacontract.org/2004/07/Contract.DTOs/CommandService/Execute", ReplyAction="http://schemas.datacontract.org/2004/07/Contract.DTOs/CommandService/ExecuteRespo" +
            "nse")]
        System.Threading.Tasks.Task ExecuteAsync(object command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommandServiceChannel : HeavenlyPizzeriaWebUI.CommandService.CommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<HeavenlyPizzeriaWebUI.CommandService.CommandService>, HeavenlyPizzeriaWebUI.CommandService.CommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Execute(object command) {
            base.Channel.Execute(command);
        }
        
        public System.Threading.Tasks.Task ExecuteAsync(object command) {
            return base.Channel.ExecuteAsync(command);
        }
    }
}
